version: '3.1'

services:
  server:
    image: development2018/contest-server-d:latest
    restart: always
    environment:
      APP_SECRET: ${APP_SECRET}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_ACCESS_SECRET: ${AWS_ACCESS_SECRET}
    ports:
    - 9000:9000
    entrypoint: /root/server/./entry-point.sh

  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    restart: always
    volumes:
    - ${NFS_MOUNT}:/nfsshare
    ports:
    - 2049:2049
    environment:
      SHARED_DIRECTORY: /nfsshare
    privileged: true

  worker:
    image: development2018/video-worker-d:latest
    restart: always
    environment:
      HOST_VIDEO: ${HOST_VIDEO}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_ACCESS_SECRET: ${AWS_ACCESS_SECRET}
      LOOP_TIME: ${LOOP_TIME}
    entrypoint: /root/./entry-point.sh
