version: '3.1'

services:
  server:
    image: lfplazas10/contest-server
    restart: always
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    ports:
      - 9000:9000
    entrypoint: /root/server/bin/./play-java-starter-example -Dplay.evolutions.db.default.autoApply=true
#    networks:
#    - backend
#    depends_on:
#    - 'postgres'
#    links:
#      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - 5434:5432
#    networks:
#      - backend
#networks:
#  backend:
#    driver: "bridge"
