version: '3.1'

services:
  server:
    image: lfplazas10/contest-server:latest
    restart: always
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      NFS_IP: ${NFS_IP}
    ports:
    - 9000:9000
    privileged: true
    entrypoint: /root/server/./entry-point.sh

  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    volumes:
    - /home/ubuntu/nfs:/nfsshare
    ports:
    - 2049:2049
    environment:
      SHARED_DIRECTORY: /nfsshare
    privileged: true

  worker:
    image: alpine:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}

# Commented as we are not using the local DB anymore
#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#      POSTGRES_USER: ${DATABASE_USER}
#    ports:
#    - 5432

