version: '3.1'

services:
  server:
    image: development2018/contest-server:latest
    restart: always
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      CONNECT_NFS: ${CONNECT_NFS}
      NFS_IP: ${NFS_IP}
    ports:
    - 9000:9000
    privileged: true
    entrypoint: /root/server/./entry-point.sh

  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    restart: always
    volumes:
    - /home/ubuntu/nfs:/nfsshare
    ports:
    - 2049:2049
    environment:
      SHARED_DIRECTORY: /nfsshare
    privileged: true

  worker:
    image: development2018/video-worker:latest
    restart: always
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      HOST_VIDEO: ${HOST_VIDEO}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_ACCESS_SECRET: ${AWS_ACCESS_SECRET}
      NFS_IP: ${NFS_IP}
    entrypoint: /root/./entry-point.sh
    privileged: true

# Commented as we are not using the local DB anymore
#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#      POSTGRES_USER: ${DATABASE_USER}
#    ports:
#    - 5432

